services:
  - type: web
    name: face-analyzer
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9   # ✅ ważne: unikamy Pythona 3.13, bo nie ma wheel-i dla dlib